model:
  type: 'mt'
  name: 'mtt'
  n_blocks: 1
  n_heads: 4
  embed_dim: 16
  ff_hid_dim: 256
  tower_hid_dims: [64]
  mask_mode_if: 'none'
  att_type: 'row_col'
  multi_token: True
  rope: true
training:
  epochs: 10
  lr: 0.001
  optimizer: 'adamw'
  weight_decay: 0.00000
  batch_size: 2048
  ff_dropout: 0.0
  att_dropout: 0.0