model:
  type: 'mt'
  name: 'mmoe'
  num_experts: 8
  expert_hidden_dims: [256, 128]
  tower_hidden_dims: [64]
  embed_dim: 8

training:
  epochs: 50
  lr: 0.001
  optimizer: 'adam'
  weight_decay: 0.000001
  batch_size: 2048
  dropout: 0.2
