model:
  type: 'st'
  name: 'saint'
  n_blocks: 1
  n_heads: 4
  embed_dim: 16
  ff_hid_dim: 256
  tower_hidden_dims: [64]
  rope: true
training:
  epochs: 100
  lr: 0.001
  optimizer: 'adamw'
  weight_decay: 0.00001
  batch_size: 2048
  ff_dropout: 0.0
  att_dropout: 0.1
