st_mlp:
  model:
    parameters:
      type:
        value: 'st'
      name: 
        value: 'st_mlp'
      hidden_dims:
        values: [[256, 128, 64]]
      embed_dim:
        value: 16
  training:
    parameters:
      epochs:
        value: 100
      lr:
        values: [0.0001, 0.001, 0.01, 0.1]
      weight_decay:
        values: [0.00001]
      optimizer:
        values: ['adam']
      batch_size: 
        values: [2048]
      dropout: 
        values: [0.00, 0.10, 0.20]
mt_mlp:
  model:
    parameters:
      type:
        value: 'mt'
      name:
        value: 'mt_mlp'
      shared_hidden_dims:
        values: [[256, 128]]
      task_hidden_dims:
        values: [[64]]
      embed_dim:
        value: 16
  training:
    parameters: 
      epochs:
        value: 100
      lr: 
        values: [0.0001, 0.001, 0.01, 0.1]
      weight_decay:
        values: [0.00001]
      optimizer:
        values: ['adam']
      batch_size:
        values: [2048]
      dropout: 
        values: [0.0, 0.1, 0.2]
mmoe:
  model:
    parameters:
      type:
        value: 'mt'
      name:
        value: 'mmoe'
      num_experts:
        values: [8]
      expert_hidden_dims:
        values: [[256, 128]]
      tower_hidden_dims:
        values: [[64]]
      embed_dim:
        value: 16
  training:
    parameters:
      epochs:
        value: 100
      lr:
        values: [0.0001, 0.001, 0.01, 0.1]
      weight_decay:
        values: [0.00001]
      optimizer:
        values: ['adam']
      batch_size:
        values: [2048]
      dropout: 
        values: [0.0, 0.1, 0.2]

ple:
  model:
    parameters:
      type:
        value: 'mt'
      name:
        value: 'ple'
      num_task_experts:
        values: [2]
      num_shared_experts: 
        values: [4] 
      num_layers: 
        values: [1, 2]
      expert_hidden_dims:
        values: [[256, 128]]
      tower_hidden_dims:
        values: [[64]]
      embed_dim:
        value: 16
  training:
    parameters:
      epochs:
        value: 100
      lr:
        values: [0.0001, 0.001, 0.01, 0.1]
      weight_decay:
        values: [0.00001]
      optimizer:
        values: ['adam']
      batch_size:
        values: [2048]
      dropout: 
        values: [0.0, 0.1, 0.2]

stem:
  model:
    parameters:
      type: 
        value: 'mt'
      name:
        value: 'stem'
      num_task_experts:
        values: [2]
      num_shared_experts:
        values: [4] 
      num_layers:
        values: [1, 2]
      expert_hidden_dims:
        values: [[256, 128]]
      tower_hidden_dims:
        values: [[64]]
      embed_dim:
        values: [16]
  training:
    parameters:
      epochs:
        value: 100
      lr:
        values: [0.0001, 0.001, 0.01, 0.1]
      weight_decay:
        values: [0.00001]
      optimizer:
        values: ['adam']
      batch_size:
        values: [2048]
      dropout: 
        values: [0.0, 0.1, 0.2]

tabt:
  model:
    parameters:
      type:
        value: 'st'
      name:
        value: 'tabt'
      n_blocks:
        values: [1, 2]
      n_heads:
        values: [4]
      embed_dim:
        values: [16]
      ff_hid_dim:
        values: [256]
      tower_hidden_dims:
        values: [[64]]
  training:
    parameters:
      epochs:
        value: 100
      lr:
        values: [0.0001, 0.001, 0.01, 0.1]
      weight_decay:
        values: [0.00001]
      optimizer:
        values: ['adamw']
      batch_size:
        values: [2048]
      ff_dropout: 
        values: [0.0, 0.1, 0.2]
      att_dropout:
        values: [0.0, 0.1, 0.2]

ftt:
  model:
    parameters:
      type:
        value: 'st'
      name:
        value: 'ftt'
      n_blocks:
        values: [2]
      n_heads:
        values: [4]
      embed_dim: 
        values: [16]
      ff_hid_dim:
        values: [256]
      tower_hidden_dims:
        values: [[64]]
  training:
    parameters:
      epochs:
        value: 100
      lr:
        values: [0.0001, 0.001, 0.01, 0.1]
      weight_decay:
        values: [0.00001]
      optimizer:
        values: ['adamw']
      batch_size:
        values: [2048]
      ff_dropout: 
        values: [0.0, 0.1, 0.2]
      att_dropout:
        values: [0.0, 0.1, 0.2]

mtt:
  model:
    parameters:
      type:
        value: 'mt'
      name:
        value: 'mtt'
      n_blocks:
        values: [1]
      n_heads:
        values: [4]
      embed_dim: 
        values: [16]
      ff_hid_dim:
        values: [256]
      tower_hid_dims:
        values: [[64]]
      att_type:
        values: ['row_col']
      mask_mode_if:
        values: ['tlm', 'tlmv2']
      multi_token:
        values: [true]
  training:
    parameters:
      epochs:
        value: 100
      lr:
        values: [0.001]
      weight_decay:
        values: [0.00001]
      optimizer:
        values: ['adamw']
      batch_size:
        values: [2048]
      ff_dropout: 
        values: [0.0, 0.1, 0.2]
      att_dropout:
        values: [0.0, 0.1, 0.2]

saint:
  model:
    parameters:
      type:
        value: 'st'
      name:
        value: 'saint'
      n_blocks:
        values: [1]
      n_heads:
        values: [4]
      embed_dim:
        values: [16]
      ff_hid_dim:
        values: [256]
      tower_hidden_dims:
        values: [[64]]
  training:
    parameters:
      epochs:
        value: 100
      lr:
        values: [0.0001, 0.001, 0.01, 0.1]
      weight_decay:
        values: [0.00001]
      optimizer:
        values: ['adamw']
      batch_size:
        values: [2048]
      ff_dropout:
        values: [0.0, 0.1, 0.2]
      att_dropout:
        values: [0.0, 0.1, 0.2]
      load_pretrained_model:
        value: false
