model:
  type: 'st'
  name: 'tabt'
  n_blocks: 2
  n_heads: 4
  embed_dim: 16
  ff_hid_dim: 256
  tower_hidden_dims: [64]

training:
  epochs: 100
  lr: 0.001
  optimizer: 'adamw'
  batch_size: 2048
  weight_decay: 0.00001
  ff_dropout: 0.0
  att_dropout: 0.2
